language: scala
dist: trusty
sudo: false
jdk:
- openjdk8
scala:
- 2.12.4
- 2.11.11
script: sbt ++$TRAVIS_SCALA_VERSION test
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
